Repository Metis-Team/mts_presentation, pull requests merged in 2022-04, with the labels that each got.

#3 Add presentation addon
  .gitignore
  .hemtt/template/scripts/get_version.lua
  README.md
  addons/presentation/$PBOPREFIX$
  addons/presentation/CfgEventHandlers.hpp
  addons/presentation/XEH_PREP.hpp
  addons/presentation/XEH_postInit.sqf
  addons/presentation/XEH_preInit.sqf
  addons/presentation/XEH_preStart.sqf
  addons/presentation/config.cpp
  addons/presentation/data/Background_nav.paa
  addons/presentation/data/Background_selection.paa
  addons/presentation/data/Button_h.paa
  addons/presentation/data/Button_k_p.paa
  addons/presentation/data/Button_np.paa
  addons/presentation/data/Button_p.paa
  addons/presentation/data/Logo.paa
  addons/presentation/data/lb_bg.paa
  addons/presentation/functions/fnc_changeSlide.sqf
  addons/presentation/functions/fnc_fillSlidesCombo.sqf
  addons/presentation/functions/fnc_getTopics.sqf
  addons/presentation/functions/fnc_openDialog.sqf
  addons/presentation/functions/fnc_setDisplay.sqf
  addons/presentation/functions/fnc_setSlide.sqf
  addons/presentation/functions/fnc_startPresentation.sqf
  addons/presentation/functions/fnc_stopPresentation.sqf
  addons/presentation/functions/fnc_toggleContinueButton.sqf
  addons/presentation/functions/script_component.hpp
  addons/presentation/initKeybinds.hpp
  addons/presentation/initSettings.hpp
  addons/presentation/script_component.hpp
  addons/presentation/script_debug.hpp
  addons/presentation/script_macros.hpp
  addons/presentation/script_mod.hpp
  addons/presentation/script_version.hpp
  addons/presentation/stringtable.xml
  addons/presentation/ui/mts_presentation_dialog.hpp
  addons/presentation/ui/mts_presentation_display.hpp
  addons/presentation/ui/mts_presentation_ui_macros.hpp
  build.bat
  build_release.bat
  hemtt.toml
  include/x/cba/addons/main/script_macros_common.hpp
  mod.cpp
  mts_logo_over_small.paa
  mts_logo_small.paa
  mts_picture.paa
  sqfc.json
  tools/build.py
  tools/cba/addons/xeh/script_xeh.hpp
  tools/compile_sqf.py
  tools/make.py
  tools/setup.bat
  tools/setup.py
Labels: enhancement

#6 Untabify
  addons/presentation/XEH_postInit.sqf
Labels: cleanup, ignore changelog

#7 Change license to APL
  LICENSE
  README.md
Labels: enhancement, ignore changelog

#8 Remove duplicate picture entry in mod.cpp
  mod.cpp
Labels: bug fix
